export const abi = [
  {
    inputs: [
      {
        internalType: "contract Storage",
        name: "storageAddress",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "ContractNotFound", type: "error" },
  { inputs: [], name: "ContractPaused", type: "error" },
  { inputs: [], name: "InvalidOrOutdatedContract", type: "error" },
  { inputs: [], name: "MultisigAlreadyRegistered", type: "error" },
  { inputs: [], name: "MultisigLimitReached", type: "error" },
  { inputs: [], name: "MultisigMustBeEnabled", type: "error" },
  { inputs: [], name: "MultisigNotFound", type: "error" },
  { inputs: [], name: "MustBeGuardian", type: "error" },
  { inputs: [], name: "MustBeGuardianOrValidContract", type: "error" },
  { inputs: [], name: "MustBeMultisig", type: "error" },
  { inputs: [], name: "NoEnabledMultisigFound", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "multisig",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "actor",
        type: "address",
      },
    ],
    name: "DisabledMultisig",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "multisig",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "actor",
        type: "address",
      },
    ],
    name: "EnabledMultisig",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "multisig",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "GGPClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "multisig",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "actor",
        type: "address",
      },
    ],
    name: "RegisteredMultisig",
    type: "event",
  },
  {
    inputs: [],
    name: "MULTISIG_LIMIT",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "addr", type: "address" }],
    name: "disableMultisig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "addr", type: "address" }],
    name: "enableMultisig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "addr", type: "address" }],
    name: "getIndexOf",
    outputs: [{ internalType: "int256", name: "", type: "int256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "index", type: "uint256" }],
    name: "getMultisig",
    outputs: [
      { internalType: "address", name: "addr", type: "address" },
      { internalType: "bool", name: "enabled", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "addr", type: "address" }],
    name: "registerMultisig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "requireNextActiveMultisig",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "version",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawUnclaimedGGP",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];