export const abi = [
  {
    inputs: [
      {
        internalType: "contract Storage",
        name: "storageAddress",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "ContractNotFound", type: "error" },
  { inputs: [], name: "ContractPaused", type: "error" },
  { inputs: [], name: "InvalidOrOutdatedContract", type: "error" },
  { inputs: [], name: "MustBeGuardian", type: "error" },
  { inputs: [], name: "MustBeGuardianOrValidContract", type: "error" },
  { inputs: [], name: "MustBeMultisig", type: "error" },
  { inputs: [], name: "NotAllowed", type: "error" },
  {
    inputs: [{ internalType: "address", name: "defender", type: "address" }],
    name: "addDefender",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "defenders",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "disableAllMultisigs",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "pauseEverything",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "defender", type: "address" }],
    name: "removeDefender",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "resumeEverything",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "version",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
];